M48
; DRILL file KiCad 10.0.4 date 2026-08-08T00:18:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-08T00:18:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X208.9Y-105.8
T2
X229.9Y-105.8
T3
X158.9Y-88.25
X158.9Y-104.4
X184.1Y-95.5
M30
